name: cyber
version: 0.1.0
description: Cybersecurity domain pack for CVE triage
classes:
  - CVE
  - Product
  - Vendor
  - Technique
  - Event
relations:
  - AFFECTS
  - MITIGATES
  - RELATED_TO
  - REQUIRES
  - NEXT_IF
questions_file: questions.yaml


